site_name: KrakeBlog
site_description: A blog hosted on GitHub Pages
site_author: Kevin Kraemer
site_url: https://krake747.github.io/krake-blog/

repo_name: krake747/krake-blog
repo_url: https://github.com/krake747/krake-blog

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Montserrat
    code: JetBrains Mono

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2024 Kevin Kraemer –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - blog
